# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"

  # Python dependencies (uv)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    groups:
      # Group pytest and related plugins
      testing:
        patterns:
          - "pytest*"
      # Group linting and formatting tools
      linting:
        patterns:
          - "ruff"
          - "mypy"
          - "bandit"
      # Group all other dependencies
      production:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "bandit"
